server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3

hearing:
  api:
    url: ${HEARING_API_URL:http://rd-commondata-api-aat.service.core-compute-aat.internal}

idam:
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${S2S_SECRET:Y6OORUQWPMUEM3QH}
    microservice: fis_hmc_api
  api:
    url: ${IDAM_API_BASEURL:https://idam-api.aat.platform.hmcts.net}
core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.hmc.api.controllers

#If you use a database then uncomment below lines and update db properties accordingly
#spring:

amqp:
  host: ${AMQP_HOST:hmc-servicebus-demo.servicebus.windows.net}
  sharedAccessKeyName: ${AMQP_SHARED_ACCESS_KEY_NAME:SendAndListenSharedAccessKey}
  jrd:
    topic: ${AMQP_TOPIC_NAME:hmc-to-cft-demo}
    sharedAccessKeyValue: ${AMQP_SHARED_ACCESS_KEY_VALUE:dummy}
    subscription: ${AMQP_SUBSCRIPTION:hmc-fis-subscription-demo}

azure:
  application-insights:
    instrumentation-key: ${fis.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


thread:
  count: ${THREAD_COUNT:4}
logging:
  level:
    org:
      springframework:
        web: DEBUG
