server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/fis-kv/"
  application:
    name: fis-hmc-api
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

hearing:
  api:
    url: ${HEARING_API_URL:http://rd-commondata-api-demo.service.core-compute-demo.internal}
  search-case-type-id: PRLAPPS
  specialCharacters: \.[]{}()<>*-=!?^$|

cafcass:
  excludeHearingStates: HEARING_REQUESTED,AWAITING_LISTING,EXCEPTION,CANCELLATION_SUBMITTED,UPDATE_SUBMITTED
ref_data_venue:
  api:
    url: ${REF_DATA_VENUE_URL:http://rd-location-ref-api-demo.service.core-compute-demo.internal/}

ref_data_judicial:
  api:
    url: ${REF_DATA_JUDICIAL_URL:http://rd-judicial-api-demo.service.core-compute-demo.internal/}
idam:
  url: ${IDAM_API_URL:https://idam-api.aat.platform.hmcts.net}
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    totp_secret: ${OIDC_S2S_SECRET:dummy}
    microservice: ${OIDC_S2S_MICROSERVICE_NAME:fis_hmc_api}
  api:
    url: ${IDAM_API_URL:https://idam-api.aat.platform.hmcts.net}
  client:
    id: ${FIS_HMC_IDAM_CLIENT_ID:fis-hmc-client-api}
    baseUrl: ${IDAM_API_URL:https://idam-api.demo.platform.hmcts.net}
    redirect_uri: ${MANAGE_CASE_REDIRECT_URL:https://manage-case.demo.platform.hmcts.net/oauth2/callback}
    secret: ${FIS_HMC_IDAM_CLIENT_SECRET:dummy}
    authorize:
      context-path: /oauth2/authorize
    token:
      context-path: /oauth2/token
  refDataUserAuth:
    username: ${FIS_HMC_IDAM__USER_NAME:dummy}
    password: ${IDAM_HMC_COMPONENT_USER_PASSWORD:dummy}
  system-update:
    username: ${PRL_IDAM_USER_NAME:dummy}
    password: ${IDAM_HMC_COMPONENT_USER_PASSWORD:dummy}
  hearingCftUserAuth:
    username: ${PRL_IDAM_USER_NAME:dummy}
    password: ${IDAM_HMC_COMPONENT_USER_PASSWORD:dummy}

prl:
  baseUrl: ${PRL_URL:https://prl-cos-pr-1038.preview.platform.hmcts.net/}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

ccd:
  ui:
    url: ${CCD_UI_URL:https://manage-case.aat.platform.hmcts.net/cases/case-details/}
  elastic-search-api:
    result-size: 100
    boost: 2.0

hearing_component:
  api:
    url: ${HMC_CFT_HEARING_BASEURL:http://hmc-cft-hearing-service-demo.service.core-compute-demo.internal/hearings/}
    feign-url: ${HMC_CFT_HEARING_BASEURL_FOR_FEIGN:http://hmc-cft-hearing-service-demo.service.core-compute-demo.internal/}
  futureHearingStatus: HEARING_REQUESTED, AWAITING_LISTING, LISTED, UPDATE_REQUESTED, UPDATE_SUBMITTED, EXCEPTION, CANCELLATION_REQUESTED, CANCELLATION_SUBMITTED, AWAITING_ACTUALS
  futureHearingStatusForNonCancel: HEARING_REQUESTED, AWAITING_LISTING, LISTED, UPDATE_REQUESTED, UPDATE_SUBMITTED, EXCEPTION, AWAITING_ACTUALS
  familyCourtIds: 10, 18, 25

springdoc:
  packagesToScan: uk.gov.hmcts.reform.hmc.api.controllers

#If you use a database then uncomment below lines and update db properties accordingly
#spring:

amqp:
  host: ${HMC_HOST:hmc-servicebus-demo.servicebus.windows.net}
  sharedAccessKeyName: "SendAndListenSharedAccessKey"
  jrd:
    topic: ${HMC_FIS_TOPIC_NAME:hmc-to-cft-demo}
    sharedAccessKeyValue: ${HMC_TOPIC_SHARED_ACCESS_KEY:dummy}
    subscription: ${HMC_FIS_SUBSCRIPTION_NAME:hmc-fis-subs-prl-demo}
#If you use a database then uncomment below lines and update db properties accordingly

azure:
  app_insights_key: ${APP_INSIGHTS_KEY:true}
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_KEY:00000000-0000-0000-0000-000000000000}

thread:
  count: ${THREAD_COUNT:4}
logging:
  level:
    org:
      springframework:
        web: INFO

role-assignment-service:
  api:
    url: ${ROLE_ASSIGNMENT_SERVICE_URL:http://am-role-assignment-service-aat.service.core-compute-aat.internal}

private-law:
  hmc-authorised-services: ${PRL_HMC_S2S_AUTHORISED_SERVICES:xui_webapp,prl_cos_api,fis_hmc_api}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}
