server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/fis-kv/"
  application:
    name: fis-hmc-api
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

hearing:
  api:
    url: ${HEARING_API_URL:http://rd-commondata-api-demo.service.core-compute-demo.internal}

idam:
  url: ${IDAM_API_URL:https://idam-api.demo.platform.hmcts.net}
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-demo.service.core-compute-demo.internal}
    totp_secret: ${OIDC_S2S_SECRET:dummy}
    microservice: ${OIDC_S2S_MICROSERVICE_NAME:fis_hmc_api}
  api:
    url: ${IDAM_API_BASEURL:https://idam-api.demo.platform.hmcts.net}
  serviceAccount:
    clientId: ${HMC_FIS_HEARING_SERVICE_CLIENT_ID:hmc-fis-hearing-service}
    clientSecret: ${HMC_FIS_HEARING_SERVICE_CLIENT_SECRET:dummy}
    grantType: ${IDAM_HMC_COMPONENT_GRANT_TYPE:password}
    username: ${IDAM_HMC_COMPONENT_USER_NAME:prl_hearing_manager@justice.gov.uk}
    password: ${IDAM_HMC_COMPONENT_USER_PASSWORD:dummy}
    scope: openid profile roles

prl:
  baseUrl: ${PRL_URL:http://prl-cos-demo.service.core-compute-demo.internal/}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-demo.service.core-compute-demo.internal}

ccd:
  ui:
    url: ${CCD_UI_URL:https://manage-case-hearings-int.demo.platform.hmcts.net/cases/case-details/}

hearing_component:
  api:
    url: ${HMC_CFT_HEARING_BASEURL:http://hmc-cft-hearing-service-demo.service.core-compute-demo.internal/hearings/}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.hmc.api.controllers

#If you use a database then uncomment below lines and update db properties accordingly
#spring:

amqp:
  host: ${HMC_HOST:hmc-servicebus-demo.servicebus.windows.net}
  sharedAccessKeyName: "SendAndListenSharedAccessKey"
  jrd:
    topic: ${HMC_FIS_TOPIC_NAME:hmc-to-cft-demo}
    sharedAccessKeyValue: ${HMC_TOPIC_SHARED_ACCESS_KEY:dummy}
    subscription: ${HMC_FIS_SUBSCRIPTION_NAME:hmc-fis-subs-prl-demo}
#If you use a database then uncomment below lines and update db properties accordingly

azure:
  application-insights:
    instrumentation-key: ${fis.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

thread:
  count: ${THREAD_COUNT:4}
logging:
  level:
    org:
      springframework:
        web: DEBUG

private-law:
  hmc-authorised-services: ${PRL_HMC_S2S_AUTHORISED_SERVICES:xui_webapp}
