server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3

hearing:
  api:
    url: ${HEARING_API_URL:http://rd-commondata-api-demo.service.core-compute-demo.internal}

azure:
  service-bus:
    connection-string: ${ASB_CONNECTION_STRING:dummy}
    topic-name:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${S2S_SECRET:Y6OORUQWPMUEM3QH}
    microservice: fis_hmc_api
  api:
    url: ${IDAM_API_BASEURL:https://idam-api.demo.platform.hmcts.net}
core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.demo.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/rpe/"
  application:
    name: fis_hmc_api
