java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

environment:
  CASE_DATA_STORE_BASEURL: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal'
  ROLE_ASSIGNMENT_SERVICE_URL: 'http://am-role-assignment-service-aat.service.core-compute-aat.internal'


