java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/fis/hmc-api:latest'
  ingressHost: privatelaw-hearings-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: fis
  keyVaults:
    fis-kv:
      secrets:
        - name: hmc-topic-shared-access-key
          alias: HMC_TOPIC_SHARED_ACCESS_KEY
        - name: fis-hmc-api-s2s-secret
          alias: OIDC_S2S_SECRET
        - name: AppInsightsInstrumentationKey
          alias: APP_INSIGHTS_KEY
  environment:
    REFORM_TEAM: fis
    REFORM_SERVICE_NAME: fis-hmc-api
    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net'
    HMC_FIS_TOPIC_NAME: 'hmc-to-cft-{{ .Values.global.environment }}'
    HMC_FIS_SUBSCRIPTION_NAME: 'hmc-fis-subs-prl-{{ .Values.global.environment }}'
    HMC_HOST: 'hmc-servicebus-{{ .Values.global.environment }}.servicebus.windows.net'
    APPLICATION_NAME: 'fis_hmc_api'
    HMC_CFT_HEARING_BASEURL: 'http://hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/hearings/'
    CASE_DATA_STORE_BASEURL: 'http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CCD_UI_URL: 'https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net/cases/case-details/'
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    OIDC_S2S_MICROSERVICE_NAME: 'fis_hmc_api'
    PRL_URL: 'http://prl-cos-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'

