java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/fis/hmc-api:latest'
  ingressHost: fis-hmc-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: fis

  environment:
    NODE_ENV: production
    REFORM_TEAM: fis
    REFORM_SERVICE_NAME: fis-hmc-api
    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'
    HMC_FIS_TOPIC_NAME: 'hmc-to-cft-{{ .Values.global.environment }}'
    HMC_FIS_SUBSCRIPTION_NAME: 'hmc-fis-subscription-{{ .Values.global.environment }}'

  keyVaults:
    fis-kv:
      secrets:
        - name: hmc-fis-servicebus-connection-string
          alias: HMC_FIS_SERVICEBUS_CONNECTION_STRING
        - name: AppInsightsInstrumentationKey
          alias: APP_INSIGHTS_KEY
